version: '3.3'
services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: postgres.Dockerfile
    command: postgres -c shared_buffers=256MB -c max_connections=200 -c listen_addresses='*'
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=psql_user
      - POSTGRES_PASSWORD=psql_password
      - POSTGRES_DB=greasy_slop_stops_llc
    volumes:
      - postgres-data:/var/lib/postgresql/data/

  pgadmin:
    container_name: pgadmin
    image: docker.io/dpage/pgadmin4:9.1.0
    ports:
      - 8081:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.com
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
      - PGADMIN_DISABLE_POSTFIX=true
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./servers.json:/pgadmin4/servers.json

volumes:
  postgres-data:
