CREATE SCHEMA COMPANY_DB;

CREATE TABLE COMPANY_DB.MANAGERS (
	ID UUID DEFAULT GEN_RANDOM_UUID () PRIMARY KEY,
	FIRSTNAME VARCHAR(100) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL
);

CREATE TABLE COMPANY_DB.LOCATIONS (
	ID UUID DEFAULT GEN_RANDOM_UUID () PRIMARY KEY,
	ADDRESS VARCHAR(100) NOT NULL,
	CITY VARCHAR(50) NOT NULL,
	ZIP SMALLINT NOT NULL,
	STATE VARCHAR(50) NOT NULL,
	MANAGER_ID UUID REFERENCES COMPANY_DB.MANAGERS (ID)
);

CREATE TABLE COMPANY_DB.EMPLOYEES (
	ID UUID DEFAULT GEN_RANDOM_UUID () PRIMARY KEY,
	FIRSTNAME VARCHAR(100) NOT NULL,
	LASTNAME VARCHAR(100) NOT NULL,
	LOCATION_ID UUID REFERENCES COMPANY_DB.LOCATIONS (ID)
);

CREATE TABLE COMPANY_DB.EMPLOYEE_WAGES (
	ID UUID DEFAULT GEN_RANDOM_UUID () PRIMARY KEY,
	HOURLY_WAGE NUMERIC(6, 4) NOT NULL,
	EMPLOYEE_ID UUID REFERENCES COMPANY_DB.EMPLOYEES (ID)
);

--
-- CREATE GROUP ROLES

CREATE ROLE managers;

GRANT SELECT ON ALL TABLES
IN SCHEMA COMPANY_DB
TO managers;

GRANT UPDATE ON COMPANY_DB.EMPLOYEES, COMPANY_DB.EMPLOYEE_WAGES
TO managers;

CREATE ROLE employees;

GRANT SELECT ON COMPANY_DB.EMPLOYEES
TO employees;

GRANT USAGE ON SCHEMA COMPANY_DB TO managers;

GRANT USAGE ON SCHEMA COMPANY_DB TO employees;

--
-- CREATE MANAGER GROUP USERS

INSERT INTO COMPANY_DB.MANAGERS (FIRSTNAME, LASTNAME)
VALUES ('Dirk', 'Dudley');

CREATE USER dirk WITH PASSWORD 'hunter2'
IN ROLE managers;

INSERT INTO COMPANY_DB.MANAGERS (FIRSTNAME, LASTNAME)
VALUES ('Elaine', 'Harper');

CREATE USER elaine WITH PASSWORD 'qwerty123'
IN ROLE managers;

--
-- CREATE LOCATIONS

INSERT INTO COMPANY_DB.LOCATIONS (ADDRESS, CITY, ZIP, STATE, MANAGER_ID)
VALUES ('301 W King St', 'East Berlin', '17316', 'Pennsylvania', (SELECT (ID) FROM COMPANY_DB.MANAGERS WHERE (FIRSTNAME = 'Dirk')));

INSERT INTO COMPANY_DB.LOCATIONS (ADDRESS, CITY, ZIP, STATE, MANAGER_ID)
VALUES ('104 N Main St', 'Accident', '21520', 'Maryland', (SELECT (ID) FROM COMPANY_DB.MANAGERS WHERE (FIRSTNAME = 'Elaine')));

--
-- CREATE EMPLOYEE GROUP USERS

INSERT INTO COMPANY_DB.EMPLOYEES (FIRSTNAME, LASTNAME, LOCATION_ID)
VALUES ('Janine', 'Waters', (SELECT (ID) FROM COMPANY_DB.LOCATIONS WHERE (ADDRESS = '301 W King St')));

INSERT INTO COMPANY_DB.EMPLOYEE_WAGES (HOURLY_WAGE, EMPLOYEE_ID)
VALUES ('7.25', (SELECT (ID) FROM COMPANY_DB.EMPLOYEES WHERE (FIRSTNAME = 'Janine')));

CREATE USER janine WITH PASSWORD 'password1'
IN ROLE employees;

INSERT INTO COMPANY_DB.EMPLOYEES (FIRSTNAME, LASTNAME, LOCATION_ID)
VALUES ('Anthony', 'Coleman', (SELECT (ID) FROM COMPANY_DB.LOCATIONS WHERE (ADDRESS = '104 N Main St')));

INSERT INTO COMPANY_DB.EMPLOYEE_WAGES (HOURLY_WAGE, EMPLOYEE_ID)
VALUES ('7.25', (SELECT (ID) FROM COMPANY_DB.EMPLOYEES WHERE (FIRSTNAME = 'Anthony')));

CREATE USER anthony WITH PASSWORD 'hunter2'
IN ROLE employees;

--
-- ENABLE ROW LEVEL SECURITY

ALTER TABLE COMPANY_DB.EMPLOYEES
ENABLE ROW LEVEL SECURITY;

ALTER TABLE COMPANY_DB.EMPLOYEE_WAGES
ENABLE ROW LEVEL SECURITY;

--
-- GRANT EMPLOYEE THE ABILITY TO SEE THEIR OWN ROW IN THE EMPLOYEES TABLE

CREATE POLICY employee_employees
ON COMPANY_DB.EMPLOYEES
TO employees
USING (LOWER(FIRSTNAME) = SESSION_USER);

--
-- GRANT MANAGER THE ABILITY TO SEE ALL LOCATIONS AND MANAGERS

CREATE POLICY manager_locations
ON COMPANY_DB.LOCATIONS
TO managers;

CREATE POLICY manager_managers
ON COMPANY_DB.MANAGERS
TO managers;

--
-- GRANT MANAGER THE ABILITY TO SEE AND UPDATE ALL EMPLOYEES AT THE LOCATION THEY MANAGE

CREATE POLICY manager_employees
ON COMPANY_DB.EMPLOYEES
TO managers
USING (LOCATION_ID = (SELECT (ID) FROM COMPANY_DB.LOCATIONS WHERE (MANAGER_ID = (SELECT (ID) FROM COMPANY_DB.MANAGERS WHERE (LOWER(FIRSTNAME) = SESSION_USER)))));

--
-- GRANT MANAGER THE ABILITY TO SEE AND UPDATE THE WAGES OF ALL EMPLOYEES AT THE LOCATION THEY MANAGE

CREATE POLICY manager_employee_wages
ON COMPANY_DB.EMPLOYEE_WAGES
TO managers
USING (EMPLOYEE_ID = (SELECT (ID) FROM COMPANY_DB.EMPLOYEES WHERE (LOCATION_ID = (SELECT (ID) FROM COMPANY_DB.LOCATIONS WHERE (MANAGER_ID = (SELECT (ID) FROM COMPANY_DB.MANAGERS WHERE (LOWER(FIRSTNAME) = SESSION_USER)))))));